/**
 * Tests for the interactive-prompt detector that prevents node_exec from
 * hanging when a remote command sits at sudo/yes-no/etc. waiting for input.
 *
 * The detector is the small `looksLikeInteractivePrompt` function used by
 * the cmd_stream handler in the node registry. We import the registry and
 * simulate stream messages to verify the registry calls reject early.
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import {
  registerNode,
  sendCommandStreaming,
  handleNodeMessage,
} from '../skills/nodes/node-registry.mjs';

const USER = 'user_prompttest';
const NODE = 'prompt-test-node';

// Stand up a fake WebSocket so registerNode + sendCommand have something to
// "send" to. We capture sent JSON payloads to inspect the cmdId.
function makeFakeWs() {
  const sent = [];
  return {
    readyState: 1, OPEN: 1,
    send: (data) => { sent.push(JSON.parse(data)); },
    close: () => {},
    _sent: sent,
  };
}

beforeEach(() => {
  // Each test gets a fresh node to avoid revocation/reconnect interference.
});

function fakeRegister(nodeId) {
  const ws = makeFakeWs();
  registerNode(ws, USER, {
    nodeId, hostname: nodeId, platform: 'linux', distro: 'd', arch: 'x',
    shell: '/sh', packageManager: 'apt',
  });
  return ws;
}

describe('interactive prompt detection in cmd_stream', () => {
  it('aborts a command early when sudo password prompt appears in stdout', async () => {
    const ws = fakeRegister(`${NODE}-sudo`);
    const promise = sendCommandStreaming(`${NODE}-sudo`, USER, { type: 'exec', command: 'pihole disable' }, () => {});

    // Find the cmdId the registry generated by inspecting what was sent
    const sentExec = ws._sent.find(m => m.type === 'exec');
    expect(sentExec).toBeTruthy();
    const cmdId = sentExec.cmdId;

    // Simulate the agent streaming back partial output ending in a sudo prompt
    handleNodeMessage(`${NODE}-sudo`, { type: 'cmd_stream', cmdId, stream: 'stdout', data: '[sudo] password for shawn: ' });

    await expect(promise).rejects.toThrow(/waiting for interactive input/);
  });

  it('aborts on plain "Please enter your password" (Pi-hole style)', async () => {
    const ws = fakeRegister(`${NODE}-pihole`);
    const promise = sendCommandStreaming(`${NODE}-pihole`, USER, { type: 'exec', command: 'pihole disable' }, () => {});
    const cmdId = ws._sent.find(m => m.type === 'exec').cmdId;

    handleNodeMessage(`${NODE}-pihole`, { type: 'cmd_stream', cmdId, stream: 'stdout', data: 'Please enter your password: ' });
    await expect(promise).rejects.toThrow(/Please enter your password/);
  });

  it('aborts on yes/no confirmation prompts', async () => {
    const ws = fakeRegister(`${NODE}-yn`);
    const promise = sendCommandStreaming(`${NODE}-yn`, USER, { type: 'exec', command: 'rm -rf /var/lib/foo' }, () => {});
    const cmdId = ws._sent.find(m => m.type === 'exec').cmdId;

    handleNodeMessage(`${NODE}-yn`, { type: 'cmd_stream', cmdId, stream: 'stdout', data: 'Continue? (y/n) ' });
    await expect(promise).rejects.toThrow(/waiting for interactive input/);
  });

  it('aborts on ssh first-connect prompt', async () => {
    const ws = fakeRegister(`${NODE}-ssh`);
    const promise = sendCommandStreaming(`${NODE}-ssh`, USER, { type: 'exec', command: 'ssh new.host' }, () => {});
    const cmdId = ws._sent.find(m => m.type === 'exec').cmdId;

    handleNodeMessage(`${NODE}-ssh`, {
      type: 'cmd_stream', cmdId, stream: 'stdout',
      data: 'Are you sure you want to continue connecting (yes/no/[fingerprint])? ',
    });
    await expect(promise).rejects.toThrow(/waiting for interactive input/);
  });

  it('does NOT trigger on "password" appearing mid-stream with newline (legitimate output)', async () => {
    const ws = fakeRegister(`${NODE}-fp`);
    const promise = sendCommandStreaming(`${NODE}-fp`, USER, { type: 'exec', command: 'grep password /etc/foo' }, () => {});
    const cmdId = ws._sent.find(m => m.type === 'exec').cmdId;

    // Output line ends with newline → finished line, not a prompt
    handleNodeMessage(`${NODE}-fp`, { type: 'cmd_stream', cmdId, stream: 'stdout', data: 'app_password: secret123\n' });
    handleNodeMessage(`${NODE}-fp`, { type: 'cmd_stream', cmdId, stream: 'stdout', data: 'next line\n' });

    // Promise should still be pending (no rejection)
    let settled = false;
    promise.then(() => { settled = true; }, () => { settled = true; });
    await new Promise(r => setTimeout(r, 30));
    expect(settled).toBe(false);

    // Clean up the still-pending command
    handleNodeMessage(`${NODE}-fp`, { type: 'cmd_result', cmdId, stdout: 'done', stderr: '', exitCode: 0 });
    await promise;
  });

  it('only triggers once per command (does not double-reject)', async () => {
    const ws = fakeRegister(`${NODE}-once`);
    const promise = sendCommandStreaming(`${NODE}-once`, USER, { type: 'exec', command: 'sudo x' }, () => {});
    const cmdId = ws._sent.find(m => m.type === 'exec').cmdId;

    handleNodeMessage(`${NODE}-once`, { type: 'cmd_stream', cmdId, stream: 'stdout', data: '[sudo] password for x: ' });
    // Second prompt-shaped message after we already rejected — should be a no-op
    handleNodeMessage(`${NODE}-once`, { type: 'cmd_stream', cmdId, stream: 'stdout', data: 'Sorry, try again.' });

    await expect(promise).rejects.toThrow();
  });
});
