/**
 * routes/telegram.mjs
 * Per-user Telegram bot integration. Each user brings their own BotFather bot;
 * the admin only gates whether a user is allowed to configure one
 * (user.telegramAllowed). There is no shared server-wide bot.
 *
 * Endpoints:
 *   POST   /api/telegram/webhook/:userId     — per-bot webhook (no auth; per-user secret)
 *   GET    /api/telegram/me                  — current user's Telegram status
 *   POST   /api/telegram/me                  — save bot token / webhook secret
 *   DELETE /api/telegram/me                  — wipe bot config + unregister webhook
 *   POST   /api/telegram/me/register-webhook — register user's webhook URL with Telegram
 *   POST   /api/telegram/me/link             — generate a linking code (for adding a second chat)
 *   DELETE /api/telegram/me/link             — unlink the current chat (keeps bot config)
 *
 * Storage: user.telegram = { botToken, webhookSecret, chatId }
 *          user.telegramAllowed = boolean (admin-only gate; default true)
 */

import { randomBytes, timingSafeEqual } from 'crypto';
import {
  requireAuth, readBody,
  loadUsers, saveUsers,
  getUserCoordinatorAgentId,
} from './_helpers.mjs';
import { handleChatMessage, abortChat } from '../chat-dispatch.mjs';

// ── One-time linking codes ────────────────────────────────────────────────────
// Scoped to a specific user — a code generated by userA cannot link a chat on
// userB's bot. Codes are only needed to attach a *second* chat to a user; the
// very first chat to /start a freshly-registered bot is trusted on the
// assumption the user owns the bot they just configured.
const linkCodes = new Map();
const LINK_CODE_TTL = 10 * 60 * 1000;

function generateLinkCode(userId) {
  for (const [code, data] of linkCodes) if (data.expires < Date.now()) linkCodes.delete(code);
  for (const [code, data] of linkCodes) if (data.userId === userId) linkCodes.delete(code);
  const code = randomBytes(3).toString('hex').toUpperCase();
  linkCodes.set(code, { userId, expires: Date.now() + LINK_CODE_TTL });
  return code;
}

function consumeLinkCode(code, userId) {
  const data = linkCodes.get(code);
  if (!data) return false;
  if (data.expires < Date.now()) { linkCodes.delete(code); return false; }
  if (data.userId !== userId) return false;
  linkCodes.delete(code);
  return true;
}

// ── Telegram Bot API (per-user token) ────────────────────────────────────────
async function callTelegram(token, method, body) {
  if (!token) throw new Error('Telegram bot token not set');
  const resp = await fetch(`https://api.telegram.org/bot${token}/${method}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  return resp.json();
}

async function sendMessage(token, chatId, text) {
  for (const chunk of splitMessage(text)) {
    await callTelegram(token, 'sendMessage', {
      chat_id: chatId, text: chunk, parse_mode: 'HTML',
    }).catch(e => console.warn('[telegram] sendMessage failed:', e.message));
  }
}

async function sendTyping(token, chatId) {
  await callTelegram(token, 'sendChatAction', { chat_id: chatId, action: 'typing' })
    .catch(() => {});
}

// ── Markdown → Telegram HTML conversion ──────────────────────────────────────
function mdToHtml(text) {
  let result = '';
  const codeBlockRe = /```[\w]*\n?([\s\S]*?)```/g;
  let last = 0;
  let match;
  while ((match = codeBlockRe.exec(text)) !== null) {
    result += convertInline(text.slice(last, match.index));
    result += `<pre>${escHtml(match[1].trim())}</pre>`;
    last = match.index + match[0].length;
  }
  result += convertInline(text.slice(last));
  return result;
}

function convertInline(text) {
  return text
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')
    .replace(/\*(.+?)\*/g, '<i>$1</i>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\n/g, '\n');
}

function escHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function splitMessage(text, limit = 4096) {
  if (text.length <= limit) return [text];
  const chunks = [];
  let remaining = text;
  while (remaining.length > limit) {
    let cut = remaining.lastIndexOf('\n', limit);
    if (cut < limit * 0.5) cut = limit;
    chunks.push(remaining.slice(0, cut));
    remaining = remaining.slice(cut).trimStart();
  }
  if (remaining) chunks.push(remaining);
  return chunks;
}

// ── User helpers ──────────────────────────────────────────────────────────────
// Read the user's Telegram bundle, with transparent migration from the old
// top-level `telegramChatId` field (which the shared-bot implementation used).
function getUserTelegram(user) {
  if (!user) return {};
  if (user.telegram && typeof user.telegram === 'object') return user.telegram;
  if (user.telegramChatId) return { chatId: String(user.telegramChatId) };
  return {};
}

function isTelegramAllowed(user) {
  if (!user) return false;
  if (user.role === 'owner' || user.role === 'admin') return true;
  return user.telegramAllowed !== false;
}

function patchUserTelegram(userId, patch) {
  const users = loadUsers();
  const idx = users.findIndex(u => u.id === userId);
  if (idx === -1) return null;
  const existing = getUserTelegram(users[idx]);
  users[idx].telegram = { ...existing, ...patch };
  // Clean up the legacy top-level field once migrated
  delete users[idx].telegramChatId;
  saveUsers(users);
  return users[idx];
}

function clearUserTelegram(userId, opts = {}) {
  const users = loadUsers();
  const idx = users.findIndex(u => u.id === userId);
  if (idx === -1) return;
  if (opts.chatOnly) {
    if (users[idx].telegram) delete users[idx].telegram.chatId;
  } else {
    delete users[idx].telegram;
  }
  delete users[idx].telegramChatId;
  saveUsers(users);
}

// ── Outbound (scheduler, background tasks) ────────────────────────────────────
/**
 * Send a plain message to a user's linked Telegram chat using *their* bot.
 * Best-effort: returns false if the user has no bot, no linked chat, or
 * Telegram rejects the call.
 */
export async function sendTelegramToUser(userId, text) {
  const user = loadUsers().find(u => u.id === userId);
  if (!user) return false;
  const tg = getUserTelegram(user);
  if (!tg.botToken || !tg.chatId) return false;
  try { await sendMessage(tg.botToken, tg.chatId, text); return true; }
  catch (e) { console.warn('[telegram] sendTelegramToUser failed:', e.message); return false; }
}

// ── Webhook handler ───────────────────────────────────────────────────────────
async function handleWebhook(req, res, userId) {
  const user = loadUsers().find(u => u.id === userId);
  if (!user) { res.writeHead(404); res.end('Unknown user'); return; }
  const tg = getUserTelegram(user);
  if (!tg.botToken) { res.writeHead(404); res.end('Not configured'); return; }

  // Verify secret with constant-time compare. A naive char-by-char compare
  // leaks via response timing and would let an attacker reconstruct the
  // secret one byte at a time.
  const secret   = tg.webhookSecret;
  const provided = req.headers['x-telegram-bot-api-secret-token'];
  let ok = false;
  if (secret && typeof provided === 'string') {
    const a = Buffer.from(secret);
    const b = Buffer.from(provided);
    if (a.length === b.length) { try { ok = timingSafeEqual(a, b); } catch {} }
  }
  if (!ok) { res.writeHead(403); res.end('Forbidden'); return; }

  let body;
  try { body = JSON.parse(await readBody(req)); }
  catch { res.writeHead(400); res.end('Bad request'); return; }

  // Ack immediately so Telegram doesn't retry while we do LLM work
  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end('{}');

  const message = body.message ?? body.edited_message;
  if (!message) return;

  const chatId = message.chat?.id;
  const text   = message.text?.trim() ?? '';
  if (!chatId) return;
  const chatIdStr = String(chatId);

  // /start [code] — handles first-time link and multi-chat link
  const startMatch = text.match(/^\/start(?:\s+([A-F0-9]{6}))?$/i);
  if (startMatch) {
    const code = startMatch[1]?.toUpperCase();

    if (!tg.chatId) {
      // First chat to /start a freshly-registered bot is trusted — the user
      // just configured it and it's their private bot.
      patchUserTelegram(userId, { chatId: chatIdStr });
      await sendMessage(tg.botToken, chatId,
        `✓ Linked to OpenEnsemble as <b>${escHtml(user.name)}</b>.\n\nSend me a message to get started.`);
      return;
    }
    if (tg.chatId === chatIdStr) {
      await sendMessage(tg.botToken, chatId, `Already linked as <b>${escHtml(user.name)}</b>.`);
      return;
    }
    // A different chat — require explicit code
    if (code && consumeLinkCode(code, userId)) {
      patchUserTelegram(userId, { chatId: chatIdStr });
      await sendMessage(tg.botToken, chatId, '✓ This chat is now the linked chat.');
      return;
    }
    await sendMessage(tg.botToken, chatId,
      'This chat is not linked. Generate a code in OpenEnsemble → Settings → Profile → Telegram and send it as:\n\n<code>/start YOUR_CODE</code>');
    return;
  }

  // Any other command: only the linked chat may use the bot
  if (tg.chatId !== chatIdStr) {
    await sendMessage(tg.botToken, chatId,
      'This chat is not linked to OpenEnsemble. Send /start and a linking code to connect.');
    return;
  }

  if (text === '/stop') {
    abortChat(userId, getUserCoordinatorAgentId(userId));
    await sendMessage(tg.botToken, chatId, 'Stopped.');
    return;
  }

  if (text === '/help') {
    await sendMessage(tg.botToken, chatId,
      '<b>OpenEnsemble Bot</b>\n\n/start — Link this chat\n/stop — Cancel in-progress response\n/help — Show this message\n\nAnything else is sent to your coordinator agent.');
    return;
  }

  await sendTyping(tg.botToken, chatId);

  const chunks = [];
  try {
    await handleChatMessage({
      userId,
      agentId: getUserCoordinatorAgentId(userId),
      text,
      onEvent: async (e) => {
        if (e.type === 'token') {
          chunks.push(e.text);
        } else if (e.type === 'done') {
          const response = mdToHtml(chunks.join(''));
          await sendMessage(tg.botToken, chatId, response || '…');
        } else if (e.type === 'error') {
          await sendMessage(tg.botToken, chatId, `Error: ${escHtml(e.message)}`);
        } else if (e.type === 'image') {
          await sendMessage(tg.botToken, chatId, e.prompt ? `[Image] ${e.prompt}` : '[Image generated]');
        }
      },
    });
  } catch (e) {
    console.error('[telegram] handleChatMessage error:', e);
    await sendMessage(tg.botToken, chatId, 'Something went wrong. Please try again.');
  }
}

// ── Route handler ─────────────────────────────────────────────────────────────
export async function handle(req, res) {
  const json = (data, status = 200) => {
    res.writeHead(status, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(data));
    return true;
  };

  // /api/telegram/webhook/:userId  (Telegram posts here)
  const whMatch = req.url?.match(/^\/api\/telegram\/webhook\/([a-zA-Z0-9_-]+)\/?$/);
  if (whMatch && req.method === 'POST') {
    await handleWebhook(req, res, whMatch[1]);
    return true;
  }

  // Everything under /api/telegram/me is caller-scoped (uses requireAuth)
  if (req.url === '/api/telegram/me' && req.method === 'GET') {
    const userId = requireAuth(req, res); if (!userId) return true;
    const user = loadUsers().find(u => u.id === userId);
    const tg   = getUserTelegram(user);
    const out = {
      allowed:          isTelegramAllowed(user),
      botTokenSet:      Boolean(tg.botToken),
      webhookSecretSet: Boolean(tg.webhookSecret),
      linked:           Boolean(tg.chatId),
      chatId:           tg.chatId ?? null,
      webhookPath:      `/api/telegram/webhook/${userId}`,
    };
    if (tg.botToken) {
      try {
        const [me, hook] = await Promise.all([
          callTelegram(tg.botToken, 'getMe', {}),
          callTelegram(tg.botToken, 'getWebhookInfo', {}),
        ]);
        if (me?.ok) {
          out.botUsername = me.result?.username;
          out.botName     = me.result?.first_name;
        } else if (me) {
          out.tokenError = me.description ?? 'getMe failed';
        }
        if (hook?.ok) {
          out.webhookUrl             = hook.result?.url || null;
          out.webhookPendingUpdates  = hook.result?.pending_update_count ?? 0;
          out.webhookLastError       = hook.result?.last_error_message || null;
          out.webhookLastErrorDate   = hook.result?.last_error_date || null;
        }
      } catch (e) { out.telegramError = e.message; }
    }
    return json(out);
  }

  if (req.url === '/api/telegram/me' && req.method === 'POST') {
    const userId = requireAuth(req, res); if (!userId) return true;
    const user = loadUsers().find(u => u.id === userId);
    if (!isTelegramAllowed(user)) return json({ error: 'Telegram is disabled for your account' }, 403);
    let body;
    try { body = JSON.parse(await readBody(req)); } catch { return json({ error: 'Invalid JSON' }, 400); }
    const patch = {};
    if (typeof body.botToken === 'string' && body.botToken.trim())           patch.botToken      = body.botToken.trim();
    if (typeof body.webhookSecret === 'string' && body.webhookSecret.trim()) patch.webhookSecret = body.webhookSecret.trim();
    if (!Object.keys(patch).length) return json({ error: 'Nothing to save' }, 400);
    // Changing the bot token invalidates the previously-linked chat: that chat
    // belonged to a different bot, so keeping it would leak DMs if the new bot
    // is messaged from a different account.
    if (patch.botToken) {
      const existing = getUserTelegram(user);
      if (existing.botToken && existing.botToken !== patch.botToken) {
        patch.chatId = null;
      }
    }
    patchUserTelegram(userId, patch);
    return json({ ok: true });
  }

  if (req.url === '/api/telegram/me' && req.method === 'DELETE') {
    const userId = requireAuth(req, res); if (!userId) return true;
    const user = loadUsers().find(u => u.id === userId);
    const tg = getUserTelegram(user);
    if (tg.botToken) {
      try { await callTelegram(tg.botToken, 'deleteWebhook', {}); } catch {}
    }
    clearUserTelegram(userId);
    return json({ ok: true });
  }

  if (req.url === '/api/telegram/me/register-webhook' && req.method === 'POST') {
    const userId = requireAuth(req, res); if (!userId) return true;
    const user = loadUsers().find(u => u.id === userId);
    if (!isTelegramAllowed(user)) return json({ error: 'Telegram is disabled for your account' }, 403);
    let tg = getUserTelegram(user);
    if (!tg.botToken) return json({ error: 'Save a bot token first' }, 400);
    let body;
    try { body = JSON.parse(await readBody(req)); } catch { return json({ error: 'Invalid JSON' }, 400); }
    const { webhookUrl } = body;
    if (!webhookUrl) return json({ error: 'webhookUrl is required' }, 400);
    const expectedSuffix = `/api/telegram/webhook/${userId}`;
    if (!webhookUrl.endsWith(expectedSuffix)) {
      return json({ error: `Webhook URL must end with ${expectedSuffix}` }, 400);
    }
    // Auto-provision a secret if the user hasn't set one — the webhook is
    // unauthenticated otherwise, so we don't ship without this.
    if (!tg.webhookSecret) {
      const sec = randomBytes(16).toString('hex');
      patchUserTelegram(userId, { webhookSecret: sec });
      tg = { ...tg, webhookSecret: sec };
    }
    try {
      const result = await callTelegram(tg.botToken, 'setWebhook', {
        url: webhookUrl,
        allowed_updates: ['message'],
        secret_token: tg.webhookSecret,
      });
      return json(result);
    } catch (e) {
      return json({ error: e.message }, 500);
    }
  }

  if (req.url === '/api/telegram/me/link' && req.method === 'POST') {
    const userId = requireAuth(req, res); if (!userId) return true;
    const user = loadUsers().find(u => u.id === userId);
    if (!isTelegramAllowed(user)) return json({ error: 'Telegram is disabled for your account' }, 403);
    const code = generateLinkCode(userId);
    return json({ code, expiresIn: LINK_CODE_TTL / 1000 });
  }

  if (req.url === '/api/telegram/me/link' && req.method === 'DELETE') {
    const userId = requireAuth(req, res); if (!userId) return true;
    clearUserTelegram(userId, { chatOnly: true });
    return json({ ok: true });
  }

  return false;
}
